<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.testlibarary</groupId>
  <artifactId>CreateSpringContainer</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  <properties>
  	<maven.complier.target>17</maven.complier.target>
  	<maven.complier.source>17</maven.complier.source>
  </properties>
  <dependencies>
  <dependency>
    <groupId>org.springframework</groupId>
    <artifactId>spring-context</artifactId>
    <version>7.0.0-M9</version>
</dependency>
  </dependencies>
</project>